DEBUG = True
SQLALCHEMY_ECHO = False
SQLALCHEMY_DATABASE_URI = "mysql://root:123456@127.0.0.1/flask-mvc"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "utf-8"
# RELEASE_VERSION = '20200903'
